"#version 330 core\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec3 aColor;\n"
"out vec4 pixColor;\n"
"uniform mat4 proj;\n"
"uniform mat4 view;\n"
"uniform vec3 camPos;\n"
"void main()\n"
"{\n"
"   gl_Position = proj * view * vec4(aPos - camPos, 1);\n"
"   pixColor = vec4(aColor, 1);\n"
"}";